# USB-Based Water_Sensor_Mesh container-node!

# Copy .env.example to .env and set the USB_DEVICE and CONFIG_PATH variables

services:
  water_sensor_mesh-node:
    build: .
    container_name: water_sensor_meshd

    # Pass USB device through to the container
    devices:
      - "${USB_DEVICE}"

    # Mount local config file and named volume for data persistence
    volumes:
      - "${CONFIG_PATH}:/etc/water_sensor_meshd/config.yaml:ro"
      - water_sensor_mesh_data:/var/lib/water_sensor_meshd

    # Forward the container’s port 4403 to the host
    ports:
      - 4403:4403

    restart: unless-stopped

volumes:
  water_sensor_mesh_data:
